-- =============================================================================
-- X AutoHub — Esquema inicial
-- =============================================================================
-- Ejecutar en el SQL Editor de Supabase, en orden:
--   0001_schema.sql  →  0002_rls.sql  →  0003_storage.sql  →  seed.sql
--
-- Convenciones:
--   · Postgres en snake_case; el frontend en camelCase. La traducción vive en
--     src/core/supabase/mappers.ts. No cambies una sin la otra.
--   · Los ids son `bigint identity` (no uuid) para que las rutas existentes
--     (/car-details/101) y los modelos `id: number` sigan funcionando.
--   · `profiles.id` sí es uuid: espeja auth.users.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Perfiles — extiende auth.users con los datos que la app muestra
-- -----------------------------------------------------------------------------
create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  display_name  text        not null,
  email         text        not null,
  phone         text,
  location      text,
  avatar_url    text,
  -- Cuenta verificada por el equipo de X AutoHub (insignia en publicaciones).
  is_verified   boolean     not null default false,
  -- Permite publicar en el inventario propio (Auto Hub, Catálogo, noticias).
  is_admin      boolean     not null default false,
  created_at    timestamptz not null default now()
);

comment on table public.profiles is
  'Datos públicos del usuario. Se crea automáticamente al registrarse (trigger on_auth_user_created).';

-- Crea el perfil en cuanto Supabase Auth registra al usuario, tomando el
-- display_name de los metadatos que manda el formulario de registro.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, email, phone, location)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'display_name', ''),
      split_part(new.email, '@', 1)
    ),
    new.email,
    nullif(new.raw_user_meta_data ->> 'phone', ''),
    nullif(new.raw_user_meta_data ->> 'location', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- -----------------------------------------------------------------------------
-- AUTO HUB — inventario propio de X AutoHub, verificado por el equipo
-- -----------------------------------------------------------------------------
create type public.chasis_type as enum ('sedan', 'suv', 'hatchback', 'pickup');
create type public.traction_type as enum ('fwd', 'rwd', 'awd', '4x4');
create type public.fuel_type as enum ('gasoline', 'diesel', 'glp', 'electric');

create table if not exists public.auto_hub_vehicles (
  id           bigint generated by default as identity primary key,
  brand        text          not null,
  model        text          not null,
  year         smallint      not null check (year between 1900 and 2100),
  price        numeric(12,2) not null check (price >= 0),
  color        text          not null,
  mileage      integer       not null check (mileage >= 0),
  chasis_type  public.chasis_type   not null,
  doors        smallint      not null check (doors between 1 and 8),
  traction     public.traction_type not null,
  fuel         public.fuel_type     not null,
  cylinders    smallint      not null check (cylinders between 0 and 16),
  images       text[]        not null default '{}',
  description  text          not null default '',
  location     text          not null,
  -- Teléfono de contacto. text, no numérico: un 809... con formato no es un número.
  contact      text          not null,
  is_available boolean       not null default true,
  created_at   timestamptz   not null default now()
);

create index if not exists auto_hub_vehicles_available_idx
  on public.auto_hub_vehicles (is_available, created_at desc);
create index if not exists auto_hub_vehicles_brand_model_idx
  on public.auto_hub_vehicles (brand, model);

-- -----------------------------------------------------------------------------
-- CATÁLOGO — tienda propia de piezas (la que tiene carrito y checkout)
-- -----------------------------------------------------------------------------
create table if not exists public.hub_parts (
  id                  bigint generated by default as identity primary key,
  category            text          not null,
  name                text          not null,
  brand               text          not null,
  img_url             text          not null,
  images              text[]        not null default '{}',
  stars_calification  numeric(2,1)  not null default 0 check (stars_calification between 0 and 5),
  price               numeric(12,2) not null check (price >= 0),
  description         text          not null default '',
  stock               integer       not null default 0 check (stock >= 0),
  is_active           boolean       not null default true,
  created_at          timestamptz   not null default now()
);

create index if not exists hub_parts_category_idx on public.hub_parts (category) where is_active;
-- Búsqueda por nombre/marca sin distinguir acentos ni mayúsculas.
create index if not exists hub_parts_search_idx
  on public.hub_parts using gin (to_tsvector('spanish', name || ' ' || brand));

-- -----------------------------------------------------------------------------
-- HUB MARKET — clasificados publicados por la comunidad
-- -----------------------------------------------------------------------------
create type public.hub_market_category as enum ('vehiculos', 'piezas', 'accesorios');
create type public.item_condition as enum ('new', 'used');

create table if not exists public.hub_market_items (
  id           bigint generated by default as identity primary key,
  seller_id    uuid references public.profiles(id) on delete set null,
  -- Nombre del vendedor para el contenido sembrado (sin usuario real detrás).
  -- Cuando seller_id existe, el nombre sale del perfil; esto es el fallback.
  seller_name  text          not null,
  title        text          not null,
  description  text          not null default '',
  images       text[]        not null default '{}',
  price        numeric(12,2) not null check (price >= 0),
  location     text          not null,
  category     public.hub_market_category not null,
  condition    public.item_condition,
  is_featured  boolean       not null default false,
  is_active    boolean       not null default true,
  -- Especificaciones de vehículo, planas en vez de jsonb para poder filtrar
  -- por rango (año, kilometraje) con índices.
  spec_year        smallint,
  spec_mileage     integer,
  spec_hp          integer,
  spec_zero_to_100 numeric(4,1),
  spec_top_speed   integer,
  spec_brand       text,
  spec_model       text,
  created_at   timestamptz   not null default now(),
  -- Un vehículo sin año no sirve de nada en un clasificado.
  constraint hub_market_vehicle_needs_year
    check (category <> 'vehiculos' or spec_year is not null)
);

create index if not exists hub_market_items_category_idx
  on public.hub_market_items (category, created_at desc) where is_active;
create index if not exists hub_market_items_seller_idx
  on public.hub_market_items (seller_id);
create index if not exists hub_market_items_featured_idx
  on public.hub_market_items (is_featured, created_at desc) where is_active;

-- -----------------------------------------------------------------------------
-- SERVICIOS — el taller
-- -----------------------------------------------------------------------------
create table if not exists public.services (
  id          bigint generated by default as identity primary key,
  icon        text    not null,
  title       text    not null,
  description text    not null,
  sort_order  smallint not null default 0,
  is_active   boolean not null default true
);

-- -----------------------------------------------------------------------------
-- NOTICIAS
-- -----------------------------------------------------------------------------
create type public.news_scope as enum ('internacional', 'local');

create table if not exists public.news (
  id           bigint generated by default as identity primary key,
  title        text          not null,
  text         text          not null,
  text_large   text          not null default '',
  image_url    text          not null,
  images       text[]        not null default '{}',
  scope        public.news_scope not null,
  author       text,
  published_at date          not null default current_date,
  is_published boolean       not null default true
);

create index if not exists news_published_idx
  on public.news (published_at desc) where is_published;

-- -----------------------------------------------------------------------------
-- SOCIAL HUB — feed, clubes y eventos
-- -----------------------------------------------------------------------------
create table if not exists public.social_clubs (
  id          bigint generated by default as identity primary key,
  name        text    not null,
  location    text    not null,
  focus       text    not null,
  description text    not null default '',
  image_url   text,
  members     integer not null default 0 check (members >= 0),
  is_official boolean not null default false,
  created_at  timestamptz not null default now()
);

create table if not exists public.social_posts (
  id           bigint generated by default as identity primary key,
  author_id    uuid references public.profiles(id) on delete cascade,
  -- Fallback igual que en hub_market_items: contenido sembrado sin usuario real.
  author_name  text        not null,
  author_club  text,
  text         text        not null,
  image_url    text,
  tags         text[]      not null default '{}',
  likes        integer     not null default 0 check (likes >= 0),
  comments     integer     not null default 0 check (comments >= 0),
  created_at   timestamptz not null default now()
);

create index if not exists social_posts_recent_idx on public.social_posts (created_at desc);

create table if not exists public.social_events (
  id          bigint generated by default as identity primary key,
  title       text          not null,
  event_date  date          not null,
  location    text          not null,
  organizer   text          not null,
  description text          not null default '',
  image_url   text,
  attendees   integer       not null default 0 check (attendees >= 0),
  price       numeric(12,2) not null default 0 check (price >= 0),
  created_at  timestamptz   not null default now()
);

create index if not exists social_events_upcoming_idx on public.social_events (event_date);

-- -----------------------------------------------------------------------------
-- CLUB X AUTOHUB — suscripciones al correo (formulario del home)
-- -----------------------------------------------------------------------------
create table if not exists public.club_subscriptions (
  id         bigint generated by default as identity primary key,
  email      text        not null unique,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- CHECKOUT — opciones configurables y pedidos
-- -----------------------------------------------------------------------------
create table if not exists public.shipping_options (
  id          text          primary key,   -- 'standard', 'express', 'pickup'
  label       text          not null,
  description text          not null,
  price       numeric(12,2) not null default 0 check (price >= 0),
  eta_label   text          not null,
  sort_order  smallint      not null default 0,
  is_active   boolean       not null default true
);

create table if not exists public.payment_methods (
  id          text     primary key,        -- 'card', 'transfer', 'mercadopago'
  label       text     not null,
  description text     not null,
  sort_order  smallint not null default 0,
  is_active   boolean  not null default true
);

create type public.order_status as enum ('pending', 'paid', 'shipped', 'delivered', 'cancelled');

create table if not exists public.orders (
  id                 uuid primary key default gen_random_uuid(),
  -- Nulo permitido: se puede comprar sin cuenta (checkout de invitado).
  user_id            uuid references public.profiles(id) on delete set null,
  contact_email      text          not null,
  contact_phone      text,
  full_name          text          not null,
  address_line1      text          not null,
  city               text,
  postal_code        text,
  shipping_option_id text          not null references public.shipping_options(id),
  payment_method_id  text          not null references public.payment_methods(id),
  order_notes        text,
  subtotal           numeric(12,2) not null check (subtotal >= 0),
  shipping_price     numeric(12,2) not null default 0 check (shipping_price >= 0),
  total              numeric(12,2) not null check (total >= 0),
  status             public.order_status not null default 'pending',
  created_at         timestamptz   not null default now()
);

create index if not exists orders_user_idx on public.orders (user_id, created_at desc);

create table if not exists public.order_items (
  id         bigint generated by default as identity primary key,
  order_id   uuid   not null references public.orders(id) on delete cascade,
  part_id    bigint references public.hub_parts(id) on delete set null,
  -- Copia del nombre y precio al momento de comprar: si la pieza cambia de
  -- precio después, el pedido histórico no se altera.
  name       text          not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity   integer       not null check (quantity > 0)
);

create index if not exists order_items_order_idx on public.order_items (order_id);
