-- =============================================================================
-- X AutoHub — Módulo de administración
-- =============================================================================
--
-- Tres piezas:
--
--   1. `releases` — el historial de versiones del sitio, editable por admin.
--   2. `admin_list_users()` — listar usuarios con su correo, que las políticas de
--      columna de 0006 esconden a cualquier sesión normal.
--   3. `set_user_admin()` — dar o quitar admin a otro usuario, que el trigger de
--      0005 y la política de `profiles` bloquean desde el navegador.
--
-- Las dos funciones son `security definer` y **empiezan comprobando que quien
-- llama sea admin**. Sin esa comprobación serían un agujero peor que el que
-- cerró 0005: `security definer` se salta RLS por completo.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Historial de versiones
-- -----------------------------------------------------------------------------

create table if not exists public.releases (
  id           bigint generated by default as identity primary key,
  -- Semver sin la 'v': '0.1.0'. Único, porque una versión no se publica dos veces.
  version      text        not null unique,
  released_at  date        not null default current_date,
  title        text        not null,
  summary      text        not null default '',
  -- Los puntos del cambelog, uno por elemento. Plano en vez de jsonb: solo se
  -- listan en orden, nunca se consultan por dentro.
  changes      text[]      not null default '{}',
  -- Permite redactar una versión antes de mostrarla.
  is_published boolean     not null default true,
  created_at   timestamptz not null default now(),
  constraint releases_version_format check (version ~ '^\d+\.\d+\.\d+$')
);

create index if not exists releases_released_at_idx
  on public.releases (released_at desc);

alter table public.releases enable row level security;

-- Lectura pública solo de lo publicado: el historial de versiones es
-- información que cualquiera puede ver, como el changelog de cualquier producto.
create policy "las versiones publicadas son visibles para todos"
  on public.releases for select
  using (is_published or public.is_admin());

create policy "solo admin administra las versiones"
  on public.releases for all
  using (public.is_admin())
  with check (public.is_admin());


-- -----------------------------------------------------------------------------
-- 2. Listar usuarios (con correo) para el panel
-- -----------------------------------------------------------------------------
-- 0006 le quitó `email` y `phone` a las claves anon y authenticated, así que un
-- admin tampoco los ve con un select normal: los permisos de columna son por
-- rol, no por condición. Esta función los devuelve, pero solo a un admin.

create or replace function public.admin_list_users()
returns table (
  id           uuid,
  display_name text,
  email        text,
  phone        text,
  location     text,
  is_admin     boolean,
  is_verified  boolean,
  created_at   timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Solo un administrador puede ver los usuarios.' using errcode = '42501';
  end if;

  return query
    select p.id, p.display_name, p.email, p.phone, p.location,
           p.is_admin, p.is_verified, p.created_at
    from public.profiles p
    order by p.created_at desc;
end;
$$;

revoke all on function public.admin_list_users() from public;
grant execute on function public.admin_list_users() to authenticated;


-- -----------------------------------------------------------------------------
-- 3. Dar o quitar admin y verificado
-- -----------------------------------------------------------------------------
-- Dos cosas lo impiden desde el navegador, las dos a propósito:
--   - La política de update de `profiles` solo deja editar tu propia fila.
--   - El trigger `freeze_profile_privileges` (0005) congela `is_admin` e
--     `is_verified` salvo para la `service_role`.
--
-- Esta función es la puerta controlada: se salta ambas cosas, pero solo si quien
-- llama ya es admin. El trigger reconoce el paso legítimo por un ajuste local a
-- la transacción, que nadie puede poner desde PostgREST.

create or replace function public.freeze_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(auth.role(), '') <> 'service_role'
     and coalesce(current_setting('app.allow_privilege_change', true), '') <> 'on' then
    new.is_admin    := old.is_admin;
    new.is_verified := old.is_verified;
  end if;
  return new;
end;
$$;

create or replace function public.set_user_admin(
  p_user_id     uuid,
  p_is_admin    boolean,
  p_is_verified boolean default null
)
returns table (id uuid, display_name text, is_admin boolean, is_verified boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caller uuid := auth.uid();
begin
  if not public.is_admin() then
    raise exception 'Solo un administrador puede cambiar permisos.' using errcode = '42501';
  end if;

  -- Un admin no se quita el admin a sí mismo: dejaría el panel sin dueño si es
  -- el único, y es un error fácil de cometer con un clic.
  if p_user_id = v_caller and p_is_admin is false then
    raise exception 'No puedes quitarte a ti mismo el acceso de administrador.'
      using errcode = '22023';
  end if;

  if not exists (select 1 from public.profiles where profiles.id = p_user_id) then
    raise exception 'Ese usuario no existe.' using errcode = '22023';
  end if;

  perform set_config('app.allow_privilege_change', 'on', true);

  update public.profiles p
     set is_admin    = p_is_admin,
         is_verified = coalesce(p_is_verified, p.is_verified)
   where p.id = p_user_id;

  perform set_config('app.allow_privilege_change', 'off', true);

  return query
    select p.id, p.display_name, p.is_admin, p.is_verified
    from public.profiles p
    where p.id = p_user_id;
end;
$$;

revoke all on function public.set_user_admin(uuid, boolean, boolean) from public;
grant execute on function public.set_user_admin(uuid, boolean, boolean) to authenticated;


-- -----------------------------------------------------------------------------
-- Primera versión, la que este repo acaba de etiquetar
-- -----------------------------------------------------------------------------

insert into public.releases (version, released_at, title, summary, changes)
values (
  '0.1.0',
  '2026-08-14',
  'Backend en vivo y auditoría de seguridad cerrada',
  'Supabase pasa a ser la fuente de datos real y se cierran los huecos de seguridad que aparecieron al conectarlo.',
  array[
    'Supabase conectado y verificado contra la base real: esquema, RLS, storage y seed.',
    'Los pedidos se crean en una función de Postgres: el precio lo pone el servidor.',
    'Cerrada una escalada de privilegios: un usuario registrado podía hacerse administrador.',
    'Arreglado el checkout sin cuenta, que creaba el pedido y luego fallaba.',
    'El correo y el teléfono de los perfiles dejan de ser públicos.',
    'Los guards esperan la restauración de la sesión: recargar ya no saca al usuario.',
    'Cerrada una redirección abierta en el inicio de sesión.',
    'Angular 21.2.20: seis vulnerabilidades XSS corregidas.',
    'Fuentes sin licencia comercial reemplazadas por alternativas SIL OFL.',
    'Video del home de 2.5 MB a 791 KB y logo de 77 KB a 19 KB.',
    'Los botones de agregar al carrito ahora se alcanzan con el teclado.'
  ]
)
on conflict (version) do nothing;
